project:
  type: website

website:
  title: "tabby"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/tabby/
  repo-actions: [edit, issue]
  sidebar:
    logo: "https://github.com/user-attachments/assets/2b293570-727a-4ca2-85e6-0c308108772a"
    logo-alt: "A hexagon logo for the tabby extension."
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/tabby/
    contents: 
      - text: "Home"
        file: index.qmd
      - text: "Examples"
        file: qtabby-example.qmd
      - section: "Support"
        contents:
        - text: "FAQ"
          href: qtabby-faq.qmd
        - text: "Submit an issue"
          href: https://github.com/coatless-quarto/tabby/issues/new/choose
      - section: "Extra"
        contents:
        - qtabby-release-notes.qmd

format: 
  html:
    toc: true